---
title: "iteration_and_listcols"
author: "Martha Mulugeta"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(echo = TRUE)
set.seed(1)
```

```{r}
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
l
```

```{r}
l$vec_numeric

l$summary

##pulls second thing in list - matrix
l[[2]]

mean(l$vec_numeric)
```

```{r}
df = list(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

df$a
df[[2]]
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
##compute mean and standard deviation for each list element
mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
mean_and_sd(df[[3]])
mean_and_sd(df[[4]])
```

```{r}
##using for loops to compute mean and standard deviation for each list element
output = vector("list", length = 4)
```

Write our first for loop
```{r}
for (i in 1:4) {
  
  output[[i]] = mean_and_sd(df[[i]])
  
}

##instead of for loop, use map for mean and sd of each element in list
output = map(df, mean_and_sd)

##could also do for median and summary 
output_median = map(df, median)
output_summary = map(df, summary)

##could also do this based on what you know/expect
output_median = map_dbl(df, median)
output = map_dfr(df, mean_and_sd)

##map everything in input list into mean and standard deviation and this is where it should go; more explicit, not changing results
output = map(df, ~mean_and_sd(.x))
```

##Napolean
```{r}
read_page_reviews = function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  data_frame(title, stars, text)
}
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_urls = str_c(url_base, 1:5)

vec_urls 

output = vector("list", length = 5)

for (i in 1:5) {
  
  output[[i]] = read_page_reviews(vec_urls[[i]])

}

output = map(vec_urls, read_page_reviews)
```

##list columns

```{r}
weather = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2016-01-01",
    date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Nest within station
```{r}
weather_nest = 
  weather %>% 
  nest(data = date:tmin)
```

Is the list column really a list?

```{r}
weather_nest %>% pull(name)
weather_nest %>% pull(data)

weather_nest$data[[1]]

##back to original dataset by unnesting
weather_nest %>% 
  unnest()
```

##Operations on list columns

Can I do useful things with a list column?

```{r}
central_park_df = weather_nest$data[[1]]

##fit linear model for Central Park
lm(tmax ~ tmin, data = central_park_df)

##fit linear model for all three
lm(tmax ~ tmin, data = weather_nest$data[[1]])
lm(tmax ~ tmin, data = weather_nest$data[[2]])
lm(tmax ~ tmin, data = weather_nest$data[[3]])
```

Try a loop
```{r}
weather_lm = function(df) {
  
  lm(tmax ~ tmin, data = df)
}
```

```{r}
output = vector("list", length = 3)
for (i in 1:3) {
  
  output[[i]] = weather_lm(weather_nest$data[[i]])
  
}

output = map(weather_nest$data, weather_lm)
```

```{r}
weather_nest %>% 
  mutate(lin_models = map(data, weather_lm)) %>% 
  select(-data) %>% 
  filter(name != "CentralPark_NY")
```

##Revisit Napolean again
```{r}
napolean = 
tibble(
  page = 1:5,
  urls = str_c(url_base, page)
) %>%
  mutate(
    reviews = map(urls, read_page_reviews)
  ) %>% 
  unnest(reviews) %>% 
  select(-urls)
```
